GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "Vinicius Oliveira de Freitas",
  "email": "vinicius.asd@outlook.com",
  "password": "123456"
}


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "vinicius.asd@outlook.com",
  "password": "123456"
}

###
GET http://localhost:3000/store
Content-Type: application/json

###
POST http://localhost:3000/store
Content-Type: application/json

{
  "name": "asdasd",
  "storeUrl": "asdasd.myshopify.com",
  "userId": "82b3cf4c-a89e-41db-a189-c78beacd2c81"
}

###
PATCH http://localhost:3000/store/db7bed37-0013-4b5d-9e79-95432be1c959
Content-Type: application/json

{
    "cardFee": "4.98",
    "checkoutFee": "2.5",
    "gatewayFee": "0.99"
}


###

GET http://localhost:3000/pricings
Content-Type: application/json


###
POST http://localhost:3000/pricings
Content-Type: application/json

{
  "storeId": "db7bed37-0013-4b5d-9e79-95432be1c959",
  "productName": "Produto Teste 2",
  "productCost": "12",
  "shippingCost": "0.00",
  "marketingFee": "30"
}

###
GET http://localhost:3000/pricings/store/db7bed37-0013-4b5d-9e79-95432be1c959
Content-Type: application/json

