version: '3'

services:
  db:
    image: mysql:8.0.30-debian
    container_name: pricing-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pricing
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
